config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'application#welcome'

  # Sign up, in and log out routes
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  post '/logout', to: 'sessions#destroy', as: 'logout' 

  # for google sign in
  get "/auth/:provider/callback", to: 'sessions#create_with_google'
  
  # for GearList scope method demonstration
  get '/most_popular', to: 'gear_lists#most_popular', as: 'most_popular'


  resources :gear_lists, only: [:index] do
    resources :items, only: [:show]
    resources :trips, only: [:index]
  end
  resources :items, only: [:index, :show, :new, :create]


  resources :users do
    resources :trips, only: [:index, :new, :edit, :destroy, :show]
  end
  resources :trips, only: [:create, :update]

  # for user profile trip filter
  post '/users/:user_id/trips', to: 'trips#index'
end

app/models/trip.rb
class Trip < ApplicationRecord
    include ActiveModel::Validations
    belongs_to :user
    belongs_to :gear_list
    validates :destination, presence: true

    validates :pickup, presence: true
    validates_with PickupValidator, if: :pickup

    validates :dropoff, presence: true
    validates :gear_list, presence: true
    validates_with DropoffValidator, if: :dropoff

    scope :user_upcoming, -> (user) {where("user_id = ?", user.id).where("pickup > ?", Time.now)}
    scope :user_past, -> (user) {where("user_id = ?", user.id).where("dropoff < ?", Time.now)}


    def gear_list_attributes=(gear_list_attributes)      
        self.build_gear_list(gear_list_attributes) unless self.gear_list_id 
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

    before_action :require_login
    before_action :set_trip, except: [:new, :create, :index]

    def new
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            if @user != current_user
                redirect_to root_path, alert: "Please sign in to plan a trip"
            else
                @trip = @user.trips.build
                @gl = @trip.build_gear_list
                @gear_lists = GearList.all
            end
        else
            redirect_to user_path(current_user), alert: 'Please plan a trip from your profile'
        end
    end

    def index
        if params[:gear_list_id]
            @gear_list = GearList.find_by(id: params[:gear_list_id])
            if @gear_list
                @trips = @gear_list.trips
            else
                redirect_to root_path, alert: "That Gear List doesn't exist"
            end
        elsif params[:filter]
            user = User.find_by(id: params[:user_id])
            if user == current_user
                @trips = set_user_trips
            else 
                redirect_to user_path(user), alert: "Those aren't your trips"
            end
        else
            redirect_to user_path(current_user), alert: "You can view your trips from your profile!"
        end
    end

    def create
        @trip = current_user.trips.build(trip_params)
        if @trip.save
            redirect_to user_trip_path(current_user, @trip)
        else
            @gear_lists = GearList.all
            render 'new'
        end
    end

    def show; end

    def edit
        @gear_lists = GearList.all
    end
    
    def update
        if @trip.update(trip_params)
            redirect_to user_trip_path(current_user, @trip)
        else 
            @gear_lists = GearList.all
            render 'edit'
        end
    end
    
    def destroy
        if @trip.user != current_user
            redirect_to user_path(current_user), alert: "That trip doesn't belong to you"
        else
            @trip.delete
            redirect_to user_path(current_user), alert: "Trip cancelled!"
        end
    end

    private

    def set_user_trips
        case params[:filter]
        when 'All'
            current_user.trips
        when 'Upcoming'
            Trip.user_upcoming(current_user)
        when 'Past'
            Trip.user_past(current_user)
        end
    end

    def set_trip
        @trip = Trip.find_by(id: params[:id])
    end
    
    def trip_params
        params.require(:trip).permit(:destination, :pickup, :dropoff, :gear_list_id)
    end

end

app/helpers/trips_helper.rb
module TripsHelper
    def show_page_time_format(time)
        time.strftime('%A %B %e @ %R')
    end

    def index_table_time_format(time)
        time.strftime('%D @ %R')
    end

    def gear_list_name(obj)
        obj.gear_list.name
    end

    def user_name(trip)
        trip.user.user_name
    end
end

app/views/trips/_form.erb
<%= form_for trip do |f| %>
    <%= f.label :destination %>
    <%= f.text_field :destination %> <br>
    <%= f.label :pickup %>
    <%= f.datetime_field :pickup %> <br>
    <%= f.label :dropoff %>
    <%= f.datetime_field :dropoff %> <br>
    <%= f.label "Please select a Gear List you'd like to rent:" %>
    <%= f.select :gear_list_id, @gear_lists.collect{|g| [g.name, g.id]} %> <br>
    
    <%= f.submit %> 
<% end %>

app/views/trips/_trip.erb
<p>
<h3>Destination: <%= trip.destination %></h3> <br>
Gear Pickup: <%= show_page_time_format(trip.pickup) %> <br>
Gear Dropoff: <%= show_page_time_format(trip.dropoff) %>
</p>

<h3>Gear</h3>

<h4><%= trip.gear_list.name %></h4>

<ul>
    <% trip.gear_list.items.each do |item|%>
        <li><%= item.name %>
            <ul>
                <li>Description: <%= item.description %></li>
                <li>Condition: <%= item.condition %></li>
            </ul>
        </li>
    <% end %>
</ul>

app/views/trips/_trips.erb
<ul>
    <% trips.each do |trip| %>
        <li>
            <ul>
                <%= render partial: 'trips/trip', locals: {trip: trip} %>
                <%= button_to "Cancel Trip", user_trip_path(current_user, trip), method: :delete %>
                <%= button_to 'Edit Trip', edit_user_trip_path(current_user, trip), method: :get %>
            </ul>
        </li>
    <% end %>
</ul>

app/views/trips/edit.erb
<h1>Trip Edit Page</h1>

<%= render partial: 'form', locals:{trip: @trip} %>

app/views/trips/index.erb
<h1>Trip Index</h1>

<%= link_to 'Add a Trip', new_user_trip_path(current_user) %>

<%= render partial: 'trips', locals: {trips: @trips} %>

app/views/trips/new.erb
<h1>Plan a New Trip!</h1>

<%= render partial: 'application/errors', locals: {errors: @trip.errors.full_messages} %>

<%= render partial: 'form', locals: {trip: @trip} %>

app/views/trips/show.erb
<h1>Trip Show Page</h1>

<%= render partial: 'trip', locals: {trip: @trip} %>