config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'application#welcome'

  # Sign up, in and log out routes
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  post '/logout', to: 'sessions#destroy', as: 'logout' 

  # for google sign in
  get "/auth/:provider/callback", to: 'sessions#create_with_google'
  
  # for GearList scope method demonstration
  get '/most_popular', to: 'gear_lists#most_popular', as: 'most_popular'


  resources :gear_lists, only: [:index] do
    resources :items, only: [:show]
    resources :trips, only: [:index]
  end
  resources :items, only: [:index, :show, :new, :create]


  resources :users do
    resources :trips, only: [:index, :new, :edit, :destroy, :show]
  end
  resources :trips, only: [:create, :update]

  # for user profile trip filter
  post '/users/:user_id/trips', to: 'trips#index'
end

app/models/user.rb
class User < ApplicationRecord
    validates :user_name, presence: true
    validates :user_name, uniqueness: true
    has_secure_password
    has_many :trips
    has_many :gear_lists, through: :trips

    def self.from_omniauth(auth)
        where(user_name: auth.info.email).first_or_initialize do |user|
            user.user_name = auth.info.email
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_login, only: [:show]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def show
        user = User.find_by(id: params[:id])
        if user.nil? || user != current_user
            redirect_to user_path(current_user), alert: "That's not your profile"
        end
    end

    private

    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_upcoming_trips
        trips = current_user.trips.where("pickup > '#{Time.now}'")
    end
end

app/views/users/_form.erb
<%= form_for user do |f| %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %> <br>
    <%= f.label :password %>
    <%= f.password_field :password %> <br>
    <%= f.label :password_confirmation %> 
    <%= f.password_field :password_confirmation %> <br>
    
    <%= f.submit %>
<% end %>

app/views/users/_user_trips.erb
<ul>
    <% trips.each do |trip| %>
        <li>
            <ul>
                <%= render partial: 'trips/trip', locals: {trip: trip} %>
                <%= button_to "Cancel Trip", trip, method: :delete %>
                <%= button_to 'Edit Trip', edit_trip_path(trip) %>
            </ul>
        </li>
    <% end %>
</ul>

app/views/users/new.erb
<h1>New User Signup</h1>

<%= render partial: 'application/errors', locals: {errors: @user.errors.full_messages} %>

<%= render partial: 'form', locals: {user: @user} %>

app/views/users/show.erb
<h1><%= current_user.user_name %>'s Profile</h1>

<%= render partial: 'application/alert' %>

<%= link_to "Plan a Trip", new_user_trip_path(current_user) %> <br>


View Your Trips:
<%= button_to "All", user_trips_path(current_user), {name: 'filter'}%>
<%= button_to "Upcoming", user_trips_path(current_user), {name: 'filter'}%>
<%= button_to "Past", user_trips_path(current_user), {name: 'filter'}%>