config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'application#welcome'

  # Sign up, in and log out routes
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  post '/logout', to: 'sessions#destroy', as: 'logout' 

  # for google sign in
  get "/auth/:provider/callback", to: 'sessions#create_with_google'
  
  # for GearList scope method demonstration
  get '/most_popular', to: 'gear_lists#most_popular', as: 'most_popular'


  resources :gear_lists, only: [:index] do
    resources :items, only: [:show]
    resources :trips, only: [:index]
  end
  resources :items, only: [:index, :show, :new, :create]


  resources :users do
    resources :trips, only: [:index, :new, :edit, :destroy, :show]
  end
  resources :trips, only: [:create, :update]

  # for user profile trip filter
  post '/users/:user_id/trips', to: 'trips#index'
end

app/models/gear_list.rb
class GearList < ApplicationRecord
    has_many :items
    has_many :trips
    has_many :users, through: :trips
    validates :name, presence: true
    validates :name, uniqueness: true

    scope :most_trips, -> {order(trips: :desc).limit(5)}

end

app/controllers/gear_lists_controller.rb
class GearListsController < ApplicationController

    def index
        @gear_lists = GearList.all
    end

    def most_popular
        @gear_lists = GearList.most_trips
    end

end

app/helpers/gear_lists_helper.rb
module GearListsHelper
end

app/views/gear_lists/_gear_lists.erb
<ul>
    <% gear_lists.each do |g| %>
        <li>
            <h3><%= g.name %></h3>
            <ul>
                <% g.items.each do |i| %>
                    <li><%= i.name %> - <%= link_to 'See item', gear_list_item_path(g, i) %></li>
                <% end %>
            </ul>
        </li>
    <% end %>
</ul>

app/views/gear_lists/index.erb
<h1>Gear List Index</h1>

<h4><%= link_to "5 Most Popular Gear Lists!", most_popular_path %></h2>

<h2>All Gear Lists</h2>


<%= render partial: 'application/alert' %>


<%= render partial: 'gear_lists', locals: {gear_lists: @gear_lists} %>

app/views/gear_lists/most_popular.erb
<h1>5 Most Popular Gear Lists</h1>

<%= render partial: 'gear_lists', locals: {gear_lists: @gear_lists} %>