config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'application#welcome'

  # Sign up, in and log out routes
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  post '/logout', to: 'sessions#destroy', as: 'logout' 

  # for google sign in
  get "/auth/:provider/callback", to: 'sessions#create_with_google'
  
  # for GearList scope method demonstration
  get '/most_popular', to: 'gear_lists#most_popular', as: 'most_popular'


  resources :gear_lists, only: [:index] do
    resources :items, only: [:show]
    resources :trips, only: [:index]
  end
  resources :items, only: [:index, :show, :new, :create]


  resources :users do
    resources :trips, only: [:index, :new, :edit, :destroy, :show]
  end
  resources :trips, only: [:create, :update]

  # for user profile trip filter
  post '/users/:user_id/trips', to: 'trips#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Gear Pool Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
        <%= link_to 'Home', root_path %> | 
        <%= link_to 'Gear Packages', gear_lists_path %> | 
        <%= link_to 'Items', items_path %> | 
        <% if current_user %>
          <%= link_to 'Donate Item', new_item_path %> | 
          <%= link_to 'Profile', user_path(current_user) %> | 
          <%= link_to 'Log Out', logout_path, {method: 'post'} %>
        <% else %>
          <%= link_to 'Sign Up', signup_path %> | 
          <%= link_to 'Sign In', signin_path %> | 
          <%= link_to "Sign In with Google", '/auth/google_oauth2' %>
        <% end %>
    </div>

    <%= yield %>
  </body>
</html>